apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: alban29mh-go
  janus-idp.io/tekton: alban29mh-go
  backstage.io/kubernetes-id: alban29mh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: alban29mh-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
