apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: alban29mh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: alban29mh-go 
  name: alban29mh-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: alban29mh-go 
